### ISSUE TITLE
swanlab登录出错

### ISSUE THREAD

**Issue by uuhhuu** [xiaolin199912/Resnet50-cats_vs_dogs#1]
在anaconda创建了一个虚拟环境，然后安装了四个所需的库。在虚拟环境中输入swanlab login，返回以下错误：
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\anaconda\envs\renzhi_env\Scripts\swanlab.exe\__main__.py", line 4, in <module>
  File "D:\anaconda\envs\renzhi_env\Lib\site-packages\swanlab\__init__.py", line 2, in <module>
    from .data import (
  File "D:\anaconda\envs\renzhi_env\Lib\site-packages\swanlab\data\__init__.py", line 10, in <module>
    from .modules import (
  File "D:\anaconda\envs\renzhi_env\Lib\site-packages\swanlab\data\modules\__init__.py", line 1, in <module>
    from .audio import Audio
  File "D:\anaconda\envs\renzhi_env\Lib\site-packages\swanlab\data\modules\audio\__init__.py", line 22, in <module>
    class Audio(MediaType):
  File "D:\anaconda\envs\renzhi_env\Lib\site-packages\swanlab\data\modules\audio\__init__.py", line 23, in Audio
    SF_SUPPORT_DTYPE = [np.dtype(d) for d in ["float32", "float64", "int16", "int32"]]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\renzhi_env\Lib\site-packages\swanlab\data\modules\audio\__init__.py", line 23, in <listcomp>
    SF_SUPPORT_DTYPE = [np.dtype(d) for d in ["float32", "float64", "int16", "int32"]]
                        ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dtype'
请问作者大大这是怎么回事呀

**Comment by Zeyi-Lin** [comment]
你把numpy版本降低一下，numpy>=2.0.0会导致各种bug

**Comment by Zeyi-Lin** [comment]
pip install swanlab==0.3.11 可以解决此问题

**Comment by uuhhuu** [comment]
谢谢。我首先将numpy降低至1.26.4，依旧出现同样问题。接着将swanlab调至0.3.11，问题得到解决。
非常感谢！
